var n;
n = 5;
var s;
s = 'hello';
var s2;
s2 = 'world';
var b;
b = true;
var arr;
arr = [1, 2, 3];
var sarr;
sarr = ['hi', 'hello'];
var r = [1, 2, true, 'false'];
var t;
t = ['hello', 5];
var pi = 3.14;
console.log(typeof (pi));
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
console.log(n, s, s2, b, arr, sarr, r, pi, Color, t);
