var n;
n = 5;
var s;
s = 'hello';
var s2;
s2 = 'world';
var b;
b = true;
var arr;
arr = [1, 2, 3];
var sarr;
sarr = ['hi', 'hello'];
var r = [1, 2, true, 'false'];
var t;
t = ['hello', 5];
var pi = 3.14;
console.log(typeof (pi));
var Color;
(function (Color) {
    Color[Color["Sunday"] = 0] = "Sunday";
    Color[Color["Monday"] = 1] = "Monday";
    Color[Color["Tuesday"] = 2] = "Tuesday";
    Color[Color["wednesday"] = 3] = "wednesday";
    Color[Color["Thursday"] = 4] = "Thursday";
    Color[Color["Friday"] = 5] = "Friday";
    Color[Color["Saturday"] = 6] = "Saturday";
})(Color || (Color = {}));
;
console.log(n, s, s2, b, arr, sarr, r, pi, Color, t);
